#!/bin/sh

# Make some system commands not require sudo
for command in mount umount pacman updatedb su shutdown reboot ; do
	alias "$command=sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias bc='bc -ql'
alias ls='ls -A -hN --color=auto --group-directories-first'
alias rsync='rsync -vrPlu'
alias mkd='mkdir -pv'
alias yt='yt-dlp --embed-metadata -i'
alias yta='yt -x -f bestaudio/best'
alias ffmpeg='ffmpeg -hide_banner'

# These common commands are just too long! Abbreviate them.
alias e="$EDITOR"
alias g='git'
alias o='xdg-open'
alias y='yay'
alias t='task'
alias z='zathura'
alias ka='killall'
alias lf='lfub'
alias py='python'
alias tp='trash-put'

# Colorize commands when possible.
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

# Custom aliases
alias mci='sudo make clean install'
alias tse='tsc --target es6'
alias gtro='trans -pager less -t ro -join-sentence'
alias gten='trans -pager less -t en -join-sentence'
alias ytt='yt --skip-download --write-thumbnail'
alias yts='mpv --slang=en --fs --ytdl-raw-options=ignore-config=,sub-lang=en,write-auto-sub='
alias ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
alias jrd="cd "$HOME/Documents/journal/$(date '+%Y')" && ls -A"
alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
