#!/bin/sh

# Make some system commands not require sudo.
for command in mount umount pacman updatedb su shutdown reboot ; do
	alias "$command=sudo $command"
done; unset command

# Abbreviations

## (SC2139) Expand when used, not when defined.
alias e='$EDITOR'
alias g='git'
alias o='xdg-open'
alias y='yay'
alias t='task'
alias z='zathura'
alias ka='killall'
alias lf='lfub'
alias py='python'
alias tp='trash-put'

# Verbosity and commonly-used settings.
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias bc='bc -ql'
alias ls='ls -A -hN --color=auto --group-directories-first'
alias rsync='rsync -vrPlu'
alias mkd='mkdir -pv'
alias yt='yt-dlp --embed-metadata -i'
alias yta='yt -x -f bestaudio/best'
alias ffmpeg='ffmpeg -hide_banner'

# Use colored output
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

# General-purpose
alias gtro='trans -pager less -t ro -join-sentence'
alias gten='trans -pager less -t en -join-sentence'
alias ytt='yt --skip-download --write-thumbnail'
alias yts='mpv --slang=en --fs --ytdl-raw-options=ignore-config=,sub-lang=en,write-auto-sub='

# Dev-oriented
alias mci='sudo make clean install'
alias tse='tsc --target es6'
alias jsonfmt='prettier --stdin-filepath f.json'
alias alistp='adb shell cmd package list packages'
alias penv='source venv/bin/activate'
alias emua='emulator -avd'
alias emula='emulator -list-avds'
