#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Use a higher DPI for larger screens
xrandr --dpi 90
# Set the background with the `setbg` script
setbg &
dwmblocks &
# Uncomment to use Xresources colors/settings on startup
# xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xresources & xrdbpid=$!

autostart='xcompmgr dunst pipewire remapd'

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# Bluelight filter
blugon -S 4700 &
unclutter --timeout 2 &
flameshot &
